title: DoPerl
author_url: https://doperl.org
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/"
url: "doperl.org"

theme: minima
plugins:
  - jekyll-feed

google_analytics: G-KT9F7P72RE
